/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ConflictRouteImport } from './routes/conflict'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CasesNewRouteImport } from './routes/cases.new'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as ClientsNewRouteImport } from './routes/clients.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictRoute = ConflictRouteImport.update({
  id: '/conflict',
  path: '/conflict',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesRoute,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CasesRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/conflict': typeof ConflictRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/editor': typeof EditorRoute
  '/finance': typeof FinanceRoute
  '/library': typeof LibraryRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/tools': typeof ToolsRoute
  '/verify': typeof VerifyRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/conflict': typeof ConflictRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/editor': typeof EditorRoute
  '/finance': typeof FinanceRoute
  '/library': typeof LibraryRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/tools': typeof ToolsRoute
  '/verify': typeof VerifyRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/conflict': typeof ConflictRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/editor': typeof EditorRoute
  '/finance': typeof FinanceRoute
  '/library': typeof LibraryRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/tools': typeof ToolsRoute
  '/verify': typeof VerifyRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/new': typeof CasesNewRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/calendar'
    | '/cases'
    | '/clients'
    | '/conflict'
    | '/dashboard'
    | '/deadlines'
    | '/editor'
    | '/finance'
    | '/library'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/team'
    | '/tools'
    | '/verify'
    | '/cases/$id'
    | '/cases/new'
    | '/clients/$id'
    | '/clients/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/calendar'
    | '/cases'
    | '/clients'
    | '/conflict'
    | '/dashboard'
    | '/deadlines'
    | '/editor'
    | '/finance'
    | '/library'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/team'
    | '/tools'
    | '/verify'
    | '/cases/$id'
    | '/cases/new'
    | '/clients/$id'
    | '/clients/new'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/calendar'
    | '/cases'
    | '/clients'
    | '/conflict'
    | '/dashboard'
    | '/deadlines'
    | '/editor'
    | '/finance'
    | '/library'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/team'
    | '/tools'
    | '/verify'
    | '/cases/$id'
    | '/cases/new'
    | '/clients/$id'
    | '/clients/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CalendarRoute: typeof CalendarRoute
  CasesRoute: typeof CasesRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  ConflictRoute: typeof ConflictRoute
  DashboardRoute: typeof DashboardRoute
  DeadlinesRoute: typeof DeadlinesRoute
  EditorRoute: typeof EditorRoute
  FinanceRoute: typeof FinanceRoute
  LibraryRoute: typeof LibraryRoute
  PortalRoute: typeof PortalRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  ToolsRoute: typeof ToolsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflict': {
      id: '/conflict'
      path: '/conflict'
      fullPath: '/conflict'
      preLoaderRoute: typeof ConflictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof CasesRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

interface CasesRouteChildren {
  CasesIdRoute: typeof CasesIdRoute
  CasesNewRoute: typeof CasesNewRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesIdRoute: CasesIdRoute,
  CasesNewRoute: CasesNewRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
  ClientsNewRoute: ClientsNewRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CalendarRoute: CalendarRoute,
  CasesRoute: CasesRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  ConflictRoute: ConflictRoute,
  DashboardRoute: DashboardRoute,
  DeadlinesRoute: DeadlinesRoute,
  EditorRoute: EditorRoute,
  FinanceRoute: FinanceRoute,
  LibraryRoute: LibraryRoute,
  PortalRoute: PortalRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  ToolsRoute: ToolsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
